### ISSUE TITLE
Bridges and Integration with Solana, Cosmos & BTC Layer 2s

### ISSUE THREAD

**Issue by Nite521** [Consensys/doc.zk-evm#428]
In order for Linea to thrive, prioritizing ease of use and seamless adoption is paramount, especially considering the importance of accessibility. Reflecting on my own experience with MetaMask, I encountered challenges when attempting to transfer ETH onto the Linea chain. Despite purchasing ETH through MetaMask, the funds ended up on the Ethereum chain instead of Linea, requiring additional time and effort to rectify the situation. 

Streamlining such integrations is crucial for enhancing Linea's usability and user experience. I'm genuinely excited about Linea's potential and eager to witness its evolution. Additionally, it's worth noting that the fastest-growing chains, such as Solana and BTC layer 2 projects like Merlin Chain present significant opportunities. Proactively ensuring Linea's visibility and seamless accessibility from these chains could prove to be a lucrative strategic move along with the Cosmos echo system for maximum visibility. Example attached in image[image](https://github.com/Consensys/doc.zk-evm/assets/160452253/52b0c17b-49f9-48ac-bb11-2ea230318b31)

**Comment by jlwllmr** [comment]
@Nite521 thanks for the contribution. Please bear in mind that this is the docs repo rather than a place for general feature requests or discussion about Linea's roadmap. As I can't identify a specific docs issue here, I'll close. Feel free to reopen if I've missed something.

FWIW: depending on your region and available payment methods, you may be able to on-ramp directly onto Linea via MetaMask's Buy feature on [portfolio.metamask.io](https://portfolio.metamask.io/buy/build-quote). This may prevent you having to bridge from Ethereum mainnet in future.
